### ISSUE TITLE
It's not creating group 'chrome-remote-desktop'

### ISSUE THREAD

**Issue by vsatyamesc** [KeithIMyers/Chrome-Remote-Desktop-Ubuntu-Setup#1]
usermod: group 'chrome-remote-desktop' does not exist
Synchronizing state of chrome-remote-desktop.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable chrome-remote-desktop
Unit /lib/systemd/system/chrome-remote-desktop.service is masked, ignoring.
/dev/fd/63: line 14: /home/tor/.config/autostart/chrome-remote-desktop.desktop: No such file or directory
/dev/fd/63: line 28: Option: command not found
/dev/fd/63: line 28: /opt/google/chrome-remote-desktop/chrome-remote-desktop: Permission denied
Initial Installation Done - Please Reboot and continue following the instructios on https://kmyers.me/blog/linux/chrome-remote-desktop-on-ubuntu-20-04-setup-guide-setup-script

**Comment by KeithIMyers** [comment]
Hello,
I have a few questions so I can try to replicate this
1) What distribution are you using? 
2) Is this in bare metal or a VM? 
3) What Desktop Environment are you using?

**Comment by vsatyamesc** [comment]
I'm using Ubuntu 20.04
Droplet from Digital Ocean
slim gnome

actually, I have already used this script two times before too, both are working fine. I don't know what is happening with this one

**Comment by KeithIMyers** [comment]
The tool is designed for a desktop version of Ubuntu, DO typically installs a server version of Ubuntu which lacks the GUI and several other packages to keep things minimal. You should be able to run 

sudo apt install ununtu-desktop 

That should install most of the things you need. You also should I stall Google chrome as well. Once they is done, re-run the installation script and it should work.

**Comment by vsatyamesc** [comment]
Ok, I'm trying

**Comment by vsatyamesc** [comment]
Ok thanks running now-
here's what I did, I installed Google Chrome with --fix-broken
Installed Xcfe and slim, tho DO already had lightdm in tasksel
update and upgrade 
logged in through non-root 
started the script

**Comment by vsatyamesc** [comment]
again the above error even tho I had install ubuntu-desktop and all, google chrome and everything

**Comment by vsatyamesc** [comment]
It seems the solution is to install the remote desktop deb separately with dpk -i in the root and then install with the script in the user, also had to install lightdm slim Xfce and ubuntu desktop.

**Comment by vsatyamesc** [comment]
the script wasn't creating the chrome user group for me directly
